# Generated by Django 3.2.7 on 2021-09-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiLib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('editora', models.CharField(max_length=100)),
                ('resumo', models.TextField(max_length=255)),
                ('autor', models.CharField(max_length=100)),
            ],
        ),
    ]
